sonar.projectKey=ChapterOne-Book
sonar.projectName=ChapterOne-Book
sonar.projectVersion=1.0.0
sonar.language=java
sonar.java.source=17
sonar.java.target=17
sonar.sources=services/src/main/java
sonar.tests=services/src/test/java
sonar.java.binaries=services/target/classes
sonar.java.test.binaries=services/target/test-classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/generated-sources/**,**/generated-test-sources/**
