sonar.projectKey=ChapterOne-Book
sonar.projectName=ChapterOne-Book
sonar.projectVersion=1.0.0
sonar.language=java
sonar.java.source=17
sonar.java.target=17
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/generated-sources/**,**/generated-test-sources/**
